apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-entrypoint
  labels:
      app: {{ .Values.app.name }}
  namespace: default
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
  - port: 8081
    targetPort: 8081
