apiVersion: v1
kind: PersistentVolumeClaim 
metadata: 
  name: apiserver-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  storageClassName: apiserver-storage-cls
  selector:
    matchLabels:
      release: "stable"